

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cruddemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20021004Tzx